server:
  port: 8761
eureka:
  client:
    # 是否将其本身注册到注册中心
    register-with-eureka: false
    # 是否从注册中心获取注册信息
    fetch-register: false
    # 指定服务注册中心的 url
    service-url:
      defaultZone: http://localhost:8761/eureka/